SELECT c.symbol, c.name 
FROM Company AS c, Portfolio AS p, PortfolioItem AS pi, EarningsDate AS e
WHERE 
	p.name = 'MyPortfolio' AND p.alexaUserId = 'amzn1.ask.account.AG3AH7ORTENZGSI5ATVRSNF2V4C2QK6CH3IXLPQMPLAWCCTWZNMGGWOGNVG5E6742XCHBILJRV6IIPQHMBLZ6L7TTTZSBVXRDEC567NDTNJHCJBN5P2JXH3C7XEDD7FSHUGIDIOKG7LTDXPZUU7XGF5VXNDMCKUV7CNL7CI7DVAWKANDCHLHWCJDQYS4VITDDBVTOPJ7FSV2MQQ'
	AND pi.portfolioId = p.id
	AND pi.companyId = c.id
	AND c.id = e.companyId
	AND e.earningsDate >= '14-FEB-17'
ORDER BY c.symbol ASC